### PR TITLE
feat: add post by Siddharth1006

### PR DESCRIPTION
**Pull request by Siddharth1006**
Made a post on Creating a simple Spring Boot Application.

### CODE REVIEW

**Comment by oyepriyansh** [comment]
wrong date + adding images in this repository only work as author image on configuration

**Comment by Siddharth1006** [comment]
So, do I keep the image in the same folder as src/content/posts?

**Comment by oyepriyansh** [comment]
> I see. Will fix the date. Also, so what do I do with the image? Do I keep the image in the same folder as src/content/posts?

you can add the image somewhere else and copy the link and add it using `` tag

**Comment by Siddharth1006** [comment]
> > I see. Will fix the date. Also, so what do I do with the image? Do I keep the image in the same folder as src/content/posts?
> 
> you can add the image somewhere else and copy the link and add it using `` tag

Is it ok if I create a separate folder like ```src/content/postImgs``` and move the image there?

**Comment by oyepriyansh** [comment]
> > > I see. Will fix the date. Also, so what do I do with the image? Do I keep the image in the same folder as src/content/posts?
> > 
> > 
> > you can add the image somewhere else and copy the link and add it using `` tag
> 
> Is it ok if I create a separate folder like `src/content/postImgs` and move the image there?

adding images in this repo wont work

**Comment by Siddharth1006** [comment]
Made the respective changes. Have a look.

**Review by WilliamDavidHarrison — APPROVED** [review]

**Pull request merged**
