### PR TITLE
Add : Intro.md in Post Section

### PR DESCRIPTION
**Pull request by YashkShrivas4491**
Add : Intro in post section ☑️

### CODE REVIEW

**Comment by oyepriyansh** [comment]
Please update author file too

**Comment by YashkShrivas4491** [comment]
> Please update author file too

Done @oyepriyansh ☑️ check it once

**Comment by oyepriyansh** [comment]
> > Please update author file too
> 
> Done @oyepriyansh ☑️ check it once

the 'author.ts' file

**Comment by YashkShrivas4491** [comment]
> > > Please update author file too
> > 
> > 
> > Done @oyepriyansh ☑️ check it once
> 
> the 'author.ts' file

yaa got it , I forget about that part , thanks for reminding me

**Comment by YashkShrivas4491** [comment]
> > > Please update author file too
> > 
> > 
> > Done @oyepriyansh ☑️ check it once
> 
> the 'author.ts' file

Done ☑️ , check it one more time

**Comment by YashkShrivas4491** [comment]
@oyepriyansh Done ☑️ now it's working well according to contributing. md and now you can review and merge this PR

**Review by oyepriyansh — APPROVED** [review]

**Pull request merged**
