### PR TITLE
added myself & a post

### PR DESCRIPTION
**Pull request by rudy3333**
self explanatory

### CODE REVIEW

**Comment by rudy3333** [comment]
sorry for the mess in the PRs LOL it dosen't support \n as a newline :(

**Comment by oyepriyansh** [comment]
please fix conflicts

**Comment by oyepriyansh** [comment]
> sorry for the mess in the PRs LOL it dosen't support \n as a newline :(

use <br>

**Comment by rudy3333** [comment]
@oyepriyansh g2g now

**Review by oyepriyansh — APPROVED** [review]

**Pull request merged**
