### PR TITLE
Create how-java-works.md [Completed hacktober fest issue]

### PR DESCRIPTION
**Pull request by Soyvor**

### CODE REVIEW

**Review by oyepriyansh — COMMENTED** [review]
Wrong format, please read https://github.com/oyepriyansh/DevTweet/blob/master/CONTRIBUTING.md

**Comment by Soyvor** [comment]
okay

**Comment by oyepriyansh** [comment]
Add the post im  `src/content/posts` directory, then update your username in `src/util/authors.ts` file

**Comment by Soyvor** [comment]
Chcek out, completed the PR

**Review by oyepriyansh — APPROVED** [review]

**Comment by oyepriyansh** [comment]
lol i merged this without checking exactly while eating

**Pull request merged**
