### PR TITLE
Github Icon fix

### PR DESCRIPTION
**Pull request by ydv-ankit**
fix: issue #99 

Screenshot from 2023-10-05 22-17-01

### CODE REVIEW

**Comment by oyepriyansh** [comment]
it doesn't work on theme toggle as itspng not svg

**Comment by ydv-ankit** [comment]
It works as png also

**Comment by oyepriyansh** [comment]
> It works as png also see screenshot

if the theme toggle

**Comment by ydv-ankit** [comment]
Yes I tried work both light and dark theme and it's fine

**Comment by oyepriyansh** [comment]
> Yes I tried work both light and dark theme and it's fine

**Comment by ydv-ankit** [comment]
do I have to resolve it again??

**Comment by oyepriyansh** [comment]
We need icon not a custom image

**Comment by ydv-ankit** [comment]
Do you have any icon

**Comment by oyepriyansh** [comment]
> Do you have any icon

You should import any GitHub icon from the available libraries

**Comment by ydv-ankit** [comment]
Ok I'll find

**Comment by amrahs02** [comment]
please assign me , i will fix this .

**Comment by ydv-ankit** [comment]
Okay you solve it

**Pull request closed without merging**
